# nombre de connections que peux gerer nginx en simultane
events {
    worker_connections 1024;
}

http {
    # cette ligne permet a nginx de charger un dictionnaire qui associe les extensions de fichiers aux types associe
    include /etc/nginx/mime.types;
    # si nginx ne reconnait pas l'extension alors on defini celui par default ici
    default_type application/octet-stream;

    server {
        # Ici on dit a nginx de gerer les requetes sur le port 443 en IPV4 et IPV6
        listen 443 ssl;
        listen [::]:443 ssl;

        # Le nom de domaine
        server_name pibreiss.42.fr;

        # Chemin vers le certificat et la clef genere par SSL
        ssl_certificate /etc/nginx/ssl/inception.crt;
        ssl_certificate_key /etc/nginx/ssl/inception.key;

        # Protocols SSL/TLS supporte
        ssl_protocols TLSv1.2 TLSv1.3;

        # Dossier ou se trouvent les fichiers WordPress
        root /var/www/html;
        index index.php index.html index.htm;

        # Gestion des URL classiques
        location / {
            try_files $uri $uri/ =404;
        }

        # Redirection des requetes PHP vers le conteneur WordPress (pont entre les conteneurs)
        location ~ \.php$ {
            include snippets/fastcgi-php.conf;
            # On utilise le nom du conteneur defini dans le docker-compose
            fastcgi_pass wordpress:9000;
        }
    }
}
