[www]

# le user et le roupe sous lequel va tourner notre service
user = www-data
group = www-data

# on dit d'ecouter sur le port 9000
listen = 9000

# on autorise la lecture des variables d'env
clear_env = no
